name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: Nconnzz
        with:
          settings-file-name: ""

      - name: Commit & push
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "github-actions[bot]"
          git add -A profile-3d-contrib
          git diff --staged --quiet || git commit -m "chore: update 3d contrib"
          git push
