name: Metrics

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          user: Nconnzz
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Santiago
          config_padding: 0, 8 + 11%
          plugin_activity: yes
          plugin_activity_days: 365
          plugin_activity_limit: 10
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

      - uses: lowlighter/metrics@latest
        with:
          filename: metrics-languages.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          user: Nconnzz
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: html, css, scss, less
          plugin_languages_details: percentage, bytes-size
          plugin_languages_limit: 8
